#[derive(Debug, PartialEq)]
pub enum Error {
    BilinearMapLenError,
    CommitmentError,
    DiagonalLengthError,
    DimensionError,
    DotProductLenError,
    HadamardProductLenError,
    HadamardProductVerificationError,
    InvalidProductArgumentStatement,
    InvalidShuffleStatement,
    MultiExpVerficationError,
    ProductArgumentProofError,
    ProductArgumentVerificationError,
    SingleValueProductVerificationError,
    TensorError,
    VerificationError,
    ZeroArgumentVerificationError,
    ZeroArgumentVerificationError1,
    ZeroArgumentVerificationError2,
    ZeroArgumentVerificationError3,
}
